### PR TITLE
So you shouldn't merge it butt....

### PR DESCRIPTION
**Pull request by posix4e**
Here is an example of moving to using the hbase replication feature to do es replication.

### CODE REVIEW

**Comment by mallocator** [comment]
Ah nice, Thanks.

So in your opinion, what is the advantage of using hbase replication vs asyncbase?

**Comment by posix4e** [comment]
I can see using replication vs a client both ways. Replication should be
more effecient. I also think handling deletes and updates more carefully is
helpful. Of course i'd need to update the patch to support that. I figured
chucking this over first would more palletable.

**Comment by mallocator** [comment]
Thanks for sharing your thoughts on that. That being said, I don't see myself dedicating much time on this project in the foreseeable future as I'm focusing on other projects and the current state is fine for my use, even if it's far from perfect.

What I could offer is that I include a link to your repo at the beginning of the project readme, so that users who prefer a replication based approach know where to find one.

**Comment by posix4e** [comment]
That would be great.

**Pull request closed without merging**
